title: From lorem to ipsum 
#email:
#description:
#baseurl:
url: "https://ncolomer.github.io/"
twitter_username: n_colomer
github_username:  ncolomer

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
